### ISSUE TITLE
Show "Tracks" link in top nav

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mofo-allhands#12]
We should show "Categories" link in top nav. And what should we call it? Categories? Teams? @xmatthewx 

And maybe we should remove the "Other All-hands" link?

**Comment by xmatthewx** [comment]
Good question. Teams or maybe Tracks? Let's go with Tracks for now and then get feedback next week.

We can hide Tags until we find a good reason to use them.  

I like the link to Hawaii. I think it makes a nice statement. We could shorten the text. Maybe to "Hawaii '16" or Next? I guess it is sort of confusing, but I like showing people how this app gets more powerful as we use it multiple times.

**Comment by xmatthewx** [comment]
I renamed this as Tracks. Do we need to list Categories in json? Seems like these aren't auto listed.

**Comment by xmatthewx** [comment]
related #7

**Comment by mmmavis** [comment]
as discussed in the stand today:
1. we are going to use "Tags" instead of "Categories"
2. we are going to rename "Tags" as "Tracks"
3. enable "Tracks" nav link
