### ISSUE TITLE
[QA] Bits and pieces

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/mofo-allhands#13]
Here are some not too critical things that could be improved:
- [x] session time has a leading zero. it looks like 24-hour format. 1:30 in the afternoon appears as 01:30. (ticket filed: https://github.com/mozilla/schedule-app-data-processor/issues/38)
- [x] facilitators are listed in reverse order from spreadsheet (ticket filed: https://github.com/mozilla/schedule-app-data-processor/issues/36)

I will add more non-critical things here.

**Comment by mmmavis** [comment]
> - [x] facilitators are listed in reverse order from spreadsheet 

fixed!

**Comment by mmmavis** [comment]
> - [x] session time has a leading zero. it looks like 24-hour format. 1:30 in the afternoon appears as 01:30. 

fixed!
