### ISSUE TITLE
Landing page content

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/mofo-allhands#14]
Not urgent, but below the header/menu, it might be good to add some general info. Monday is sparse anyhow. We could add: 
- [ ] thumbnail link to [Schedule Overview](https://cloud.githubusercontent.com/assets/53411/15793163/2e956420-29b0-11e6-87b0-1293c040a5bb.png)
- [ ] footer link to gh/issues ??

**Comment by xmatthewx** [comment]
Here is a revised header and overview schedule. Link to full image in list above. 

<img width="839" alt="screenshot 2016-06-07 15 58 17" src="https://cloud.githubusercontent.com/assets/53411/15872878/c5090756-2cc9-11e6-9987-9d00a8857f29.png">

**Comment by mmmavis** [comment]
@xmatthewx should the screencap include Column A (time)?

**Comment by xmatthewx** [comment]
Sure. I'm not too concerned either way.

**Comment by xmatthewx** [comment]
Okay. Image looks too crazy, especially above the Nav. Let's link to the image from the header nav like so: 

<img width="715" alt="screenshot 2016-06-09 12 22 16" src="https://cloud.githubusercontent.com/assets/53411/15937558/6c0020c0-2e3d-11e6-8455-48dffdc19487.png">

**Comment by mmmavis** [comment]
Oops, forgot to do this yesterday. Working on adding the overview screencap on the Monday tab now.
