### ISSUE TITLE
Finish migrating sessions from GH to the app

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/mofo-allhands#19]
I created a label in the London planning repo to flag sessions after their description is migrated to the app spreadsheet. Please mark your sessions so we can catch the gaps.

@ldecoursy @OpenMatt 

https://github.com/MozillaFoundation/MoFoLondon/issues

**Comment by ldecoursy** [comment]
Done!

**Comment by xmatthewx** [comment]
We are down to 14 sessions that need their descriptions and attendees to be migrated. Mostly opps and misc: https://github.com/MozillaFoundation/MoFoLondon/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22Migrated+to+App%22+

@OpenMatt can you take these?

**Comment by xmatthewx** [comment]
thanks @edrushka for the assistance see #9 for more details

**Comment by xmatthewx** [comment]
tracking session migration in #9
