### ISSUE TITLE
Favorites appear out of order

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/mofo-allhands#21]
When you click on Favorites, is it possible to have them be listed in chronological order by day (not the order in which they were selected)?

**Comment by mmmavis** [comment]
Thanks for filing this ticket @ldecoursy 🌞

This is something to fix on the data processor part. Created this ticket: https://github.com/mozilla/schedule-app-data-processor/issues/34. I will give updates once the fix is in!

**Comment by mmmavis** [comment]
YAY FIXED 🎉 🌹

**Comment by mmmavis** [comment]
i see glitches. 😿  will fix tmr

**Comment by mmmavis** [comment]
I lied. Fixed it cuz it was bothering me 😏
