### ISSUE TITLE
Update time blocks

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/mofo-allhands#24]
Looks like some of the time blocks have changed a bit. Let's list old and new here, then try and update all at once.

**Comment by xmatthewx** [comment]
#### Add
- [x] Monday, 9:00, Registration
- [x] Fri, 6:00 Free Time (good idea to list this for tired people)

### Update
- [x] Tues, 9:00, Plenary (currently set as 9:30)
- [x] Wed, 1:00, Team Time  (currently set as 1:30)
- [x] Thu, 1:00 (currently set as 1:30)

> This unfortunately requires a find/replace in the sessions tab as well

### Rename?

Can `timeblock name` have special characters? Could we change Team Time like this:
- [ ] `Team Time Wed B` change to `Team Time (Wed 10:30)`

**Comment by mmmavis** [comment]
> Can timeblock name have special characters? Could we change Team Time like this:

This is how timeblock gets "slugified":

``` python
timeblock.strip().lower().replace(' ','-').replace(',','').replace(':','-').replace('*','').replace('&','-').replace('(','-').replace(')','-')
```

So yea, changing `Team Time Wed B` to `Team Time (Wed 10:30)` should be fine.

**Comment by xmatthewx** [comment]
This will change the way time blocks appear in the session tab. Two sets of parenthesis. Will that break anything?

Before: `Wednesday Team Time Wed A (Wednesday 09:00)`
After: `Wednesday Team Time (Wed 9:00) (Wednesday 09:00)`

**Comment by xmatthewx** [comment]
Also, there's a bug: 

This doesn't appear as an option in sessions tab: `Monday 09:00     Registration`
This should be Friday: `Monday 18:00 Free Time`

**Comment by mmmavis** [comment]
> This doesn't appear as an option in sessions tab: `Monday 09:00 Registration`

There needs to be at least one session within that timeblock for the timeblock to appear on the app. 👍 

> This should be Friday: `Monday 18:00 Free Time`

kk fixing it now!

**Comment by mmmavis** [comment]
@xmatthewx 

> This will change the way time blocks appear in the session tab. Two sets of parenthesis. Will that break anything?
> Before: Wednesday Team Time Wed A (Wednesday 09:00)
> After: Wednesday Team Time (Wed 9:00) (Wednesday 09:00)

Should be fine 😄 I made the change live - http://mozilla.github.io/mofo-allhands/2016-london/#_show-wednesday

**Comment by xmatthewx** [comment]
Cool. We should change this for all the Team Time. Let's discuss during our stand. 

### Updated timeblocks

complete list of timeblock strings for easy peasy paste: 
Registration
Welcome Reception
Breakfast
Plenary
Lunch
MoFo All-hands Opening
Afternoon Coffee Break
MoFo All-hands
Chris Beard and Mitchell Baker in MoFo homeroom
MoFo All-hands 2
Dinner
Breakfast
Team Time (Wed 9:00)
Morning Coffee Break
Team Time (Wed 10:30)
Lunch
Team Time (Wed 1:00)
Afternoon Coffee Break
Elective Time
Dinner
Breakfast
Team Time (Thu 9:00)
Morning Coffee Break
Team Time (Thu 10:30)
Lunch
Team Time (Thu 1:00)
Afternoon Coffee Break
Elective Time
Dinner
Breakfast
Team Time (Fri 9:00)
Morning Coffee Break
Team Time (Fri 10:30)
Lunch
Team Time (Fri 1:30)
Afternoon Coffee Break
MoFo All-hands
Free Time
Closing Party and Dinner

### find and replace session timeblocks

Wednesday Team Time Wed A (Wednesday 09:00)
Wednesday Team Time (Wed 9:00) (Wednesday 9:00)

Wednesday Team Time Wed B (Wednesday 10:30)
Wednesday Team Time (Wed 10:30) (Wednesday 10:30)

Wednesday Team Time Wed C (Wednesday 13:00)
Wednesday Team Time (Wed 1:00) (Wednesday 13:00)

Thursday Team Time Thu A (Thursday 09:00)
Thursday Team Time (Thu 9:00) (Thursday 9:00)

Thursday Team Time Thu C (Thursday 13:00)
Thursday Team Time (Thu 1:00) (Thursday 13:00)

Thursday Team Time Thu B (Thursday 10:30)
Thursday Team Time (Thu 10:30) (Thursday 10:30)

Friday Team Time Fri A (Friday 09:00)
Friday Team Time (Fri 9:00) (Friday 9:00)

Friday Team Time Fri B (Friday 10:30)
Friday Team Time (Fri 10:30) (Friday 10:30)

Friday Team Time Fri C (Friday 13:30)
Friday Team Time (Fri 1:30) (Friday 13:30)

**Comment by mmmavis** [comment]
Updated!

**Comment by mmmavis** [comment]
One note @xmatthewx 

Thursday Team Time Thu A (Thursday 09:00)
Thursday Team Time (Thu 9:00) (Thursday 9:00) <--- note that we still need to keep the leading 0 in the last bit `(Thursday 09:00)` to match the autogenerated values in the timeblock tab 😉
