### ISSUE TITLE
Adding "Designing a Working Open Workshop" elective session to MoFo schedule

### ISSUE THREAD

**Issue by kaythaney** [mozilla/mofo-allhands#25]
hi there! possible to add this to the main MoFo schedule? it's 3pm on June 15, led by Aurelia, myself, Zannah, open to all.

link to the etherpad / agenda here: https://public.etherpad-mozilla.org/p/mofo-wow

**Comment by xmatthewx** [comment]
@ldecoursy - I added all of the Wednesday elective sessions. Haven't looked at Thursday.

**Comment by xmatthewx** [comment]
I believe this is all done.

**Comment by kaythaney** [comment]
thank you!

On Thu, Jun 9, 2016 at 3:18 PM, matthew w notifications@github.com wrote:

> Closed #25 https://github.com/mozilla/mofo-allhands/issues/25.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/mozilla/mofo-allhands/issues/25#event-687698762, or mute
> the thread
> https://github.com/notifications/unsubscribe/AAh172TN6hz95TWvaYajr9A58YUvl6Oxks5qKGcagaJpZM4IxOnD
> .

## 

@kaythaney http://twitter.com/kaythaney/
@MozillaScience http://twitter.com/mozillascience

**Comment by kaythaney** [comment]
d'oh. the time has changed to 430pm on that wednesday. possible to amend?
last change, promise!

On Thu, Jun 9, 2016 at 4:45 PM, Kaitlin Thaney kaitlin.thaney@gmail.com
wrote:

> thank you!
> 
> On Thu, Jun 9, 2016 at 3:18 PM, matthew w notifications@github.com
> wrote:
> 
> > Closed #25 https://github.com/mozilla/mofo-allhands/issues/25.
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > https://github.com/mozilla/mofo-allhands/issues/25#event-687698762, or mute
> > the thread
> > https://github.com/notifications/unsubscribe/AAh172TN6hz95TWvaYajr9A58YUvl6Oxks5qKGcagaJpZM4IxOnD
> > .
> 
> ## 
> 
> @kaythaney http://twitter.com/kaythaney/
> @MozillaScience http://twitter.com/mozillascience

## 

@kaythaney http://twitter.com/kaythaney/
@MozillaScience http://twitter.com/mozillascience

**Comment by ldecoursy** [comment]
There's a note that it starts at 4:30 in the description. The app only (currently) has one slot for all Wednesday electives. Is that something that's easy to change, @xmatthewx?

**Comment by xmatthewx** [comment]
Since there are a few other 4:30 electives, we can add a slot. Let's keep time in Titles for other odd ones.
