### ISSUE TITLE
Add last name initial

### ISSUE THREAD

**Issue by kristinashu** [mozilla/mofo-allhands#26]
Because there are some MoFo's with the same first name, we should add a last name initial to avoid any confusion. 

<img width="775" alt="screen shot 2016-06-08 at 2 01 03 pm" src="https://cloud.githubusercontent.com/assets/1068783/15910799/78dd78f4-2d81-11e6-9151-9ea637b5b11d.png">

**Comment by xmatthewx** [comment]
@ldecoursy – do you know our duplicate names? Matt, Kristina, Sam, ....

**Comment by ldecoursy** [comment]
Kristina G will not be at all-hands unfortunately :( so you're the only Kristina (however @KevZawacki may have meant Kristina G for this one)

Other dupes
- Damian P (community member) and Damian K (Advocacy)
- Sam D (Hive Chi) and Sam B (insights)
- Steph W (Science) and Stephanie M (Advocacy)

Think that's it?

**Comment by xmatthewx** [comment]
Thanks @ldecoursy. I will fix the ones I notice and can guess the correct person.  
- Matthew W (me) and Matt T

**Comment by xmatthewx** [comment]
Done!
