### ISSUE TITLE
Show times in all section titles

### ISSUE THREAD

**Issue by edrushka** [mozilla/mofo-allhands#31]
Currently, Wednesday's Team Time shows the time right in the title. Can they all be like this? It's much easier to scan.
![screenshot 2016-06-09 12 44 05](https://cloud.githubusercontent.com/assets/4515662/15943901/e86c3cf0-2e3f-11e6-8f5e-59e10b364e99.png)

**Comment by xmatthewx** [comment]
Yes!! #24

**Comment by mmmavis** [comment]
😉
