### ISSUE TITLE
On Search put focus on input

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/mofo-allhands#33]
Not absolutely essential, but a real nice feature on mobile.

**Comment by xmatthewx** [comment]
aside: If you make these improvement here, will you need to migrate them back to the core app? In London, let's revisit the architecture topic and think about db, react, node, etc.

**Comment by mmmavis** [comment]
Since the allhands app is hotlinking the `schedule.js` on https://github.com/mozilla/schedule-app-core, for changes like this (changes we want to apply to all schedule apps) I will only have to update the `schedule.js` on the core repo.

Gonna do that now since it's just dropping one additional line of code there!

**Comment by mmmavis** [comment]
@xmatthewx this change is live now. I tested it on my iPhone - autofocusing the search field causes the screen to zoom in to that field. Feel a little weird to see that instant zoom happen right after I switched to the Search Tab. Umm...

**Comment by xmatthewx** [comment]
Zoom might feel a little weird. Is the input field not already full width? Are you on iOS?

Focus and opening keyboard is standard behavior after tapping search on Android. I like how our implementation feels on my device. 

The font-size in the input field is crazy tiny.  🔬 🔍 👀 

<img width="400" alt="screenshot 2016-06-10 00 07 35" src="https://cloud.githubusercontent.com/assets/53411/15953979/5bedba14-2e9f-11e6-88b5-597a496f4b4f.png">

**Comment by xmatthewx** [comment]
This is done. 😄

**Comment by mmmavis** [comment]
![img_1279](https://cloud.githubusercontent.com/assets/2896608/15974992/2ddda1fa-2f00-11e6-94f6-38b94a47dea6.PNG)

This is what iPhone 6 (Safari) is like after I tapped the Search Tab. Input field is full width it's just the instant zoom feels weird.

**Comment by mmmavis** [comment]
solution suggested by someone on the Internet: set input box font size to `16px`

**Comment by mmmavis** [comment]
OMG `16px` IS THE TRICK! https://github.com/mozilla/schedule-app-core/commit/76049808b8c8d5873f59c960768ce6ab21a295c1

issue fixed! 😸
