### ISSUE TITLE
[Bug Fix] - MLN Metrics & Convenings #10 - Need to correct time in app

### ISSUE THREAD

**Issue by arlissc** [mozilla/mofo-allhands#35]
@xmatthewx - this session is scheduled for 11:30am Friday but the app shows 10:30 in the details and (11:30 start) in the title.
thanks so much.

**Comment by arlissc** [comment]
@xmatthewx - I think I may have figured this out - the block of time starts at 10:30 but the specific session starts at 11:30 within that block.  If this is correct feel free to close this issue.  Thx

**Comment by xmatthewx** [comment]
That's right @arlissc, there are a few sessions that fall outside the blocks that most sessions fit. I'll add a new block, or a clarifying comment in the description so there's less ambiguity.
