### ISSUE TITLE
"Category" field for London All-hands sessions

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mofo-allhands#7]
do we plan to use this for London All-hands sessions? If so I think the values can be something like
- Mozilla-wide
- All MoFo
- Team time
- Elective (?)
- Coffee Break (?)
- (something for breakfast/lunch/dinner)

/cc @xmatthewx

**Comment by mmmavis** [comment]
not sure if "category" is necessary. We can probably just utilize "tags"

**Comment by xmatthewx** [comment]
These are the Categories I used: 
Advocacy
Food & Social
Insights
Leadership Network
MoFo
Mozilla
Ops
Participation

Should I move the Categories (Tracks) to the Tags columns?

**Comment by mmmavis** [comment]
We have decided to use "Tags(Tracks)" instead. See discussion in https://github.com/mozilla/mofo-allhands/issues/12 for detail 👍
