### ISSUE TITLE
Add session descriptions

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/mofo-allhands#9]
The moment has arrived for us to migrate the session schedule from the [planning spreadsheet](https://docs.google.com/spreadsheets/d/19lBkFBuPecVtD5IuXefbaxm-13vpfZknuXWlF3gYI-0/edit) to the [app spreadsheet](https://docs.google.com/spreadsheets/d/1TEn1AYjLUSXagxJGhOiNPbDdPxsqJsSmeI-_4pvS41U/edit). We will also need to add session descriptions. 

@ldecoursy – it would be great to onboard you and have your help/oversight, particularly for adding session descriptions from Github. (Markdown is supported. If you edit a gh comment, you can copy the markdown.)

cc @OpenMatt

**Comment by xmatthewx** [comment]
Ok. I moved everything from the planning spreadsheet to the app spreadsheet. There are probably errors and few special unicorns to adjust, but the bulk of it should be good. We still need to copy descriptions from github and figure out how we want to hand invitee names (#10) . 

cc @mmmavis

**Comment by ldecoursy** [comment]
Happy to! Let me know when/how. :)

**Comment by xmatthewx** [comment]
I have migrated session titles and times. Here are some instructions for you on making edits. 

Data is [this spreadsheet](https://docs.google.com/spreadsheets/d/1TEn1AYjLUSXagxJGhOiNPbDdPxsqJsSmeI-_4pvS41U/edit#gid=1546802594). We have a command in Chat to zap that spreadsheet into json and send it to Github for the app. Magic. You can ping me, Mavis, or Chris to run that update. Please remind us all to test things and make sure nothing broke! 

The spreadsheet is fairly self-explanatory, and Mavis included some instructions at the top of each column. A few notes: 
- `New rows` – If you insert a new row, copy and paste the formula in Column B and Column H from a row above. Column B will alert you if the ID is a duplicate. Column H will auto generate an etherpad URL. 
  ✨ 
- `ID` – ID in Column A must be unique. Order doesn't really matter (is this true Mavis? Mavis: yes!), though you'll see that Monday is 100s, Tues 200s, etc. 💯 
- `Time` & `Location` – If you need to define a new Time block or Location, please file a bug here. Edits to existing blocks can break sessions that use that block. 🕐 🕥 
- `Tags` – Should list Advocacy, Leadership Network, Ops, MoFo, Mozilla, or Food & Social. 🍷 
- `Description` – This supports markdown. Separate paragraphs by line breaks (option enter) 📝 
- `Attendees` 👪  – List these in the description.  App has a good search feature to help people to find and Star 🌟  their sessions. List people name rather than something like "all designers"
- `Facilitator` – You can name 3, one per column. 👿 😮 
- `Notes URL` – You can manually enter an etherpad URL for a session if needed. If this happens mid-week, be sure to link from the auto pad to the new pad. 📜 

Questions?

@ldecoursy @mmmavis @OpenMatt

**Comment by xmatthewx** [comment]
I've added details to a couple of production sessions for reference. See session ID 302 and 308.

**Comment by xmatthewx** [comment]
@shaghdoosti – We're prepping the schedule app for use in London. We were hoping you could add Advocacy session descriptions to the spreadsheet that populates that app. Instructions above. 

Why? Using the app is a chance for us to test the tool we use at Mozfest and other events. We've added a feature that links each session to an etherpad, making documentation more accessible during and after the event to everyone. If this test is successful, we may build out a feature that enables event attendees to add images, text, and links for rich documentation of post-its, whiteboards, etc.

**Comment by xmatthewx** [comment]
@OpenMatt – can you do this for Ops sessions?

**Comment by xmatthewx** [comment]
Besides Ops sessions, this is in good shape. Will file specific bits when needed.
